"""
Conductor — RL-Inspired Orchestration Engine for Agent Coordination.

Implements the Conductor pattern (Nielsen et al., ICLR 2026) adapted for
the FDE Code Factory. The Conductor is a lightweight meta-orchestrator that:

  1. Decomposes complex tasks into targeted subtasks
  2. Assigns subtasks to specialized agents with focused instructions
  3. Designs communication topologies (access lists) between agents
  4. Adapts workflow complexity to task difficulty (organism level)
  5. Supports recursive self-referential scaling for hard problems

Key insight from the paper: "A 7B Conductor achieves significant performance
gains beyond any individual worker by learning optimal coordination strategies."

Our adaptation maps this to the FDE distributed execution model:
  - Conductor = enhanced orchestrator that generates WorkflowPlans
  - Workers = ECS agent tasks (parametrized by role + model tier)
  - Communication topology = SCD section access permissions
  - Recursive scaling = re-entry into planning when confidence is low
  - Task adaptivity = organism ladder drives workflow complexity

Architecture:
  - Receives task + organism classification + knowledge context
  - Generates a WorkflowPlan (steps, assignments, access topology)
  - Passes plan to DistributedOrchestrator for execution
  - Monitors results and triggers recursive refinement if needed

Design decisions:
  - Conductor uses Bedrock (reasoning tier) for plan generation
  - Plans are deterministic once generated (no runtime re-planning mid-stage)
  - Recursive depth is bounded (max 2 levels) to prevent runaway cost
  - Communication topology is expressed as access lists per step
  - Task difficulty adaptivity uses organism level as primary signal

Ref: Nielsen et al. "Learning to Orchestrate Agents in Natural Language
     with the Conductor" ICLR 2026 (arXiv:2512.04388v5)
Ref: docs/design/fde-core-brain-development.md Section 3.1
Ref: docs/example/FDE design pattern/Indice Mestre (Parte 4: Orquestracao)
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)


# --- Workflow Plan Data Structures ---


class TopologyType(Enum):
    """Communication topology types between agents."""

    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"
    TREE = "tree"
    DEBATE = "debate"
    RECURSIVE = "recursive"


@dataclass
class WorkflowStep:
    """A single step in the Conductor's workflow plan.

    Maps to the Conductor paper's output format:
      - subtask: natural language instruction for the agent
      - agent_id: which agent role handles this step
      - access_list: which previous step outputs are visible

    The access_list implements the communication topology:
      - [] = no visibility to previous outputs (independent)
      - ["all"] = sees all previous step outputs
      - [0, 2] = sees outputs from steps 0 and 2 only
    """

    step_index: int
    subtask: str
    agent_role: str
    model_tier: str
    access_list: list = field(default_factory=list)
    timeout_seconds: int = 600
    retry_max: int = 3

    def has_full_access(self) -> bool:
        """Whether this step sees all previous outputs."""
        return "all" in self.access_list

    def visible_steps(self, total_steps: int) -> list[int]:
        """Resolve access list to concrete step indices."""
        if "all" in self.access_list:
            return list(range(self.step_index))
        return [i for i in self.access_list if isinstance(i, int) and i < self.step_index]


@dataclass
class WorkflowPlan:
    """Complete workflow plan generated by the Conductor.

    Represents the full coordination strategy for a task:
      - Steps define what each agent does
      - Topology defines how agents communicate
      - Metadata tracks planning decisions for observability
    """

    task_id: str
    organism_level: str
    topology_type: TopologyType
    steps: list[WorkflowStep] = field(default_factory=list)
    recursive_depth: int = 0
    confidence_threshold: float = 0.7
    planning_rationale: str = ""
    estimated_tokens: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)

    def total_steps(self) -> int:
        return len(self.steps)

    def agent_roles(self) -> list[str]:
        return list(dict.fromkeys(s.agent_role for s in self.steps))

    def model_tiers_used(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for step in self.steps:
            counts[step.model_tier] = counts.get(step.model_tier, 0) + 1
        return counts

    def to_squad_manifest_stages(self) -> dict[int, list[dict[str, Any]]]:
        """Convert workflow plan to SquadManifest stage format."""
        if self.topology_type == TopologyType.PARALLEL:
            return {1: [self._step_to_agent_spec(s) for s in self.steps]}
        elif self.topology_type == TopologyType.DEBATE:
            attempts = self.steps[:-1]
            arbiter = self.steps[-1]
            return {
                1: [self._step_to_agent_spec(s) for s in attempts],
                2: [self._step_to_agent_spec(arbiter)],
            }
        else:
            stages: dict[int, list[dict[str, Any]]] = {}
            for i, step in enumerate(self.steps):
                stages[i + 1] = [self._step_to_agent_spec(step)]
            return stages

    def _step_to_agent_spec(self, step: WorkflowStep) -> dict[str, Any]:
        return {
            "role": step.agent_role,
            "model_tier": step.model_tier,
            "stage": step.step_index + 1,
            "subtask": step.subtask,
            "access_list": step.access_list,
            "timeout_seconds": step.timeout_seconds,
            "retry_max": step.retry_max,
        }


# --- Conductor Configuration ---

_ORGANISM_COMPLEXITY: dict[str, dict[str, Any]] = {
    "O1": {"max_steps": 2, "topology": TopologyType.SEQUENTIAL, "model": "fast"},
    "O2": {"max_steps": 3, "topology": TopologyType.SEQUENTIAL, "model": "reasoning"},
    "O3": {"max_steps": 4, "topology": TopologyType.TREE, "model": "reasoning"},
    "O4": {"max_steps": 5, "topology": TopologyType.DEBATE, "model": "reasoning"},
    "O5": {"max_steps": 6, "topology": TopologyType.RECURSIVE, "model": "deep"},
}

_AGENT_CAPABILITIES: dict[str, dict[str, Any]] = {
    "swe-developer-agent": {
        "strengths": ["implementation", "refactoring", "debugging"],
        "model_tier": "reasoning",
        "cost_weight": 1.0,
    },
    "swe-architect-agent": {
        "strengths": ["design", "architecture", "decomposition"],
        "model_tier": "reasoning",
        "cost_weight": 1.0,
    },
    "swe-adversarial-agent": {
        "strengths": ["review", "security", "edge-cases"],
        "model_tier": "reasoning",
        "cost_weight": 1.0,
    },
    "swe-code-context-agent": {
        "strengths": ["navigation", "search", "understanding"],
        "model_tier": "fast",
        "cost_weight": 0.3,
    },
    "fde-tech-lead-agent": {
        "strengths": ["planning", "decomposition", "governance"],
        "model_tier": "reasoning",
        "cost_weight": 1.0,
    },
    "fde-fidelity-agent": {
        "strengths": ["validation", "scoring", "benchmarking"],
        "model_tier": "fast",
        "cost_weight": 0.3,
    },
    "reporting-agent": {
        "strengths": ["documentation", "summarization", "reporting"],
        "model_tier": "fast",
        "cost_weight": 0.2,
    },
    "swe-tech-writer-agent": {
        "strengths": ["documentation", "changelog", "adr", "readme"],
        "model_tier": "standard",
        "cost_weight": 0.5,
    },
}

MAX_RECURSIVE_DEPTH = 2


# --- Conductor Engine ---


class Conductor:
    """
    RL-Inspired Conductor for Agent Workflow Orchestration.

    The Conductor generates WorkflowPlans by:
      1. Analyzing task complexity (organism level)
      2. Selecting appropriate topology
      3. Decomposing into subtasks with targeted instructions
      4. Assigning agents based on capability matching
      5. Defining communication topology (access lists)
      6. Optionally triggering recursive refinement

    Key insight preserved from the paper: the orchestrator should generate
    FOCUSED SUBTASK INSTRUCTIONS (not just role assignments) and
    TARGETED COMMUNICATION TOPOLOGIES (not broadcast everything).
    """

    def __init__(
        self,
        bedrock_model_id: str | None = None,
        aws_region: str | None = None,
        max_recursive_depth: int = MAX_RECURSIVE_DEPTH,
        token_budget: int = 50000,
    ):
        import os

        self._model_id = bedrock_model_id or os.environ.get(
            "CONDUCTOR_MODEL_ID",
            "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        )
        self._region = aws_region or os.environ.get("AWS_REGION", "us-east-1")
        self._max_depth = max_recursive_depth
        self._token_budget = token_budget
        self._bedrock = boto3.client("bedrock-runtime", region_name=self._region)

    def generate_plan(
        self,
        task_id: str,
        task_description: str,
        organism_level: str,
        knowledge_context: dict[str, Any] | None = None,
        user_value_statement: str = "",
        available_agents: list[str] | None = None,
        recursive_depth: int = 0,
        previous_result: dict[str, Any] | None = None,
    ) -> WorkflowPlan:
        """
        Generate a WorkflowPlan for a given task.

        Args:
            task_id: Unique task identifier.
            task_description: Natural language task description.
            organism_level: Complexity classification (O1-O5).
            knowledge_context: Relevant knowledge for the task.
            user_value_statement: User value being delivered.
            available_agents: Pool of agent roles to choose from.
            recursive_depth: Current recursion level (0 = root).
            previous_result: Result from previous attempt (for recursive refinement).

        Returns:
            WorkflowPlan ready for execution by DistributedOrchestrator.
        """
        if recursive_depth > self._max_depth:
            logger.warning(
                "Max recursive depth (%d) reached for task=%s. Returning simple plan.",
                self._max_depth,
                task_id,
            )
            return self._fallback_plan(task_id, task_description, organism_level)

        complexity = _ORGANISM_COMPLEXITY.get(organism_level, _ORGANISM_COMPLEXITY["O3"])
        max_steps = complexity["max_steps"]
        default_topology = complexity["topology"]

        agent_pool = available_agents or list(_AGENT_CAPABILITIES.keys())

        plan = self._invoke_conductor_reasoning(
            task_id=task_id,
            task_description=task_description,
            organism_level=organism_level,
            max_steps=max_steps,
            default_topology=default_topology,
            agent_pool=agent_pool,
            knowledge_context=knowledge_context or {},
            user_value_statement=user_value_statement,
            recursive_depth=recursive_depth,
            previous_result=previous_result,
        )

        logger.info(
            "Conductor generated plan: task=%s topology=%s steps=%d agents=%s depth=%d",
            task_id,
            plan.topology_type.value,
            plan.total_steps(),
            plan.agent_roles(),
            recursive_depth,
        )
        return plan

    def should_recurse(
        self,
        plan: WorkflowPlan,
        execution_result: dict[str, Any],
    ) -> bool:
        """
        Determine if recursive refinement should be triggered.

        Implements the Conductor paper's recursive self-referential scaling:
        when confidence in the result is below threshold, the Conductor
        re-enters as a worker to refine the coordination strategy.
        """
        if plan.recursive_depth >= self._max_depth:
            return False

        confidence = self._assess_confidence(execution_result)

        if confidence < plan.confidence_threshold:
            logger.info(
                "Confidence %.2f below threshold %.2f - triggering recursive refinement",
                confidence,
                plan.confidence_threshold,
            )
            return True

        return False

    def refine_plan(
        self,
        original_plan: WorkflowPlan,
        execution_result: dict[str, Any],
        task_description: str,
        knowledge_context: dict[str, Any] | None = None,
    ) -> WorkflowPlan:
        """
        Generate a refined plan based on previous execution results.

        Implements recursive Conductor pattern: observes previous result
        and generates improved coordination strategy.
        """
        return self.generate_plan(
            task_id=original_plan.task_id,
            task_description=task_description,
            organism_level=original_plan.organism_level,
            knowledge_context=knowledge_context,
            available_agents=original_plan.agent_roles(),
            recursive_depth=original_plan.recursive_depth + 1,
            previous_result=execution_result,
        )

    # --- Private Methods ---

    def _invoke_conductor_reasoning(
        self,
        task_id: str,
        task_description: str,
        organism_level: str,
        max_steps: int,
        default_topology: TopologyType,
        agent_pool: list[str],
        knowledge_context: dict[str, Any],
        user_value_statement: str,
        recursive_depth: int,
        previous_result: dict[str, Any] | None,
    ) -> WorkflowPlan:
        """Invoke Bedrock to generate the workflow plan."""
        system_prompt = self._build_conductor_system_prompt(
            agent_pool, max_steps, default_topology
        )
        user_message = self._build_conductor_user_message(
            task_description=task_description,
            organism_level=organism_level,
            knowledge_context=knowledge_context,
            user_value_statement=user_value_statement,
            previous_result=previous_result,
        )

        try:
            response = self._bedrock.converse(
                modelId=self._model_id,
                messages=[
                    {"role": "user", "content": [{"text": user_message}]},
                ],
                system=[{"text": system_prompt}],
                inferenceConfig={
                    "maxTokens": 4096,
                    "temperature": 0.2,
                },
            )

            output_content = response.get("output", {}).get("message", {}).get("content", [])
            output_text = ""
            for block in output_content:
                if "text" in block:
                    output_text += block["text"]

            plan = self._parse_conductor_output(
                task_id=task_id,
                organism_level=organism_level,
                output_text=output_text,
                default_topology=default_topology,
                recursive_depth=recursive_depth,
            )

            usage = response.get("usage", {})
            plan.estimated_tokens = (
                usage.get("inputTokens", 0) + usage.get("outputTokens", 0)
            )

            return plan

        except ClientError as e:
            logger.error("Conductor Bedrock invocation failed: %s", str(e))
            return self._fallback_plan(task_id, task_description, organism_level)

    def _build_conductor_system_prompt(
        self,
        agent_pool: list[str],
        max_steps: int,
        default_topology: TopologyType,
    ) -> str:
        """Build the Conductor's system prompt."""
        agent_descriptions = []
        for i, role in enumerate(agent_pool):
            caps = _AGENT_CAPABILITIES.get(role, {})
            strengths = caps.get("strengths", [])
            tier = caps.get("model_tier", "reasoning")
            agent_descriptions.append(
                f"  Agent {i} ({role}): strengths={strengths}, tier={tier}"
            )

        agents_block = "\n".join(agent_descriptions)

        return (
            "You are the Conductor - a meta-orchestrator that designs optimal\n"
            "coordination strategies for a squad of AI engineering agents.\n\n"
            "Your task: Given a problem description, decompose it into a sequence of\n"
            "workflow steps. For each step, specify:\n"
            "1. A focused natural-language subtask instruction\n"
            "2. The agent role best suited for that subtask\n"
            "3. An access list defining which previous step outputs are visible\n\n"
            f"Available agents:\n{agents_block}\n\n"
            f"Constraints:\n"
            f"- Maximum {max_steps} steps\n"
            f"- Default topology: {default_topology.value}\n"
            "- Each subtask instruction must be FOCUSED and TARGETED (not generic)\n"
            '- Access lists control information flow: [] = independent, ["all"] = sees everything\n'
            "- Prefer minimal access (only what is needed) over broadcast\n\n"
            "Output format (JSON):\n"
            "{\n"
            '  "rationale": "Brief explanation of coordination strategy",\n'
            '  "topology": "sequential|parallel|tree|debate|recursive",\n'
            '  "steps": [\n'
            "    {\n"
            '      "subtask": "Focused instruction for the agent",\n'
            '      "agent_role": "role-name",\n'
            '      "model_tier": "fast|reasoning|deep",\n'
            '      "access_list": []\n'
            "    }\n"
            "  ]\n"
            "}\n\n"
            "Key principles (from Conductor research):\n"
            "- Decompose complex problems into targeted subtasks matching agent strengths\n"
            "- Use verification steps for high-stakes outputs\n"
            "- Allocate more steps to harder problems\n"
            "- Communication topology matters: not every agent needs to see everything\n"
            "- A planning step followed by implementation is often optimal\n"
        )

    def _build_conductor_user_message(
        self,
        task_description: str,
        organism_level: str,
        knowledge_context: dict[str, Any],
        user_value_statement: str,
        previous_result: dict[str, Any] | None,
    ) -> str:
        """Build the user message for the Conductor."""
        parts = [
            f"Task: {task_description}",
            f"Complexity: {organism_level}",
            f"User Value: {user_value_statement}",
        ]

        if knowledge_context:
            parts.append(f"Knowledge Context: {json.dumps(knowledge_context, indent=2)}")

        if previous_result:
            parts.append(
                f"\nPREVIOUS ATTEMPT RESULT (refine this):\n"
                f"{json.dumps(previous_result, indent=2)}\n\n"
                f"The previous coordination strategy produced suboptimal results. "
                f"Design an improved workflow that addresses the weaknesses observed."
            )

        return "\n\n".join(parts)

    def _parse_conductor_output(
        self,
        task_id: str,
        organism_level: str,
        output_text: str,
        default_topology: TopologyType,
        recursive_depth: int,
    ) -> WorkflowPlan:
        """Parse the Conductor's JSON output into a WorkflowPlan."""
        try:
            json_start = output_text.find("{")
            json_end = output_text.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                json_str = output_text[json_start:json_end]
                data = json.loads(json_str)
            else:
                raise ValueError("No JSON found in Conductor output")

            topology_str = data.get("topology", default_topology.value)
            try:
                topology = TopologyType(topology_str)
            except ValueError:
                topology = default_topology

            steps: list[WorkflowStep] = []
            for i, step_data in enumerate(data.get("steps", [])):
                access_list = step_data.get("access_list", [])
                normalized_access: list = []
                for item in access_list:
                    if item == "all":
                        normalized_access.append("all")
                    elif isinstance(item, int):
                        normalized_access.append(item)

                steps.append(WorkflowStep(
                    step_index=i,
                    subtask=step_data.get("subtask", f"Execute step {i}"),
                    agent_role=step_data.get("agent_role", "swe-developer-agent"),
                    model_tier=step_data.get("model_tier", "reasoning"),
                    access_list=normalized_access,
                ))

            return WorkflowPlan(
                task_id=task_id,
                organism_level=organism_level,
                topology_type=topology,
                steps=steps,
                recursive_depth=recursive_depth,
                planning_rationale=data.get("rationale", ""),
            )

        except (json.JSONDecodeError, ValueError, KeyError) as e:
            logger.warning("Failed to parse Conductor output: %s", str(e))
            return self._fallback_plan(task_id, "", organism_level)

    def _assess_confidence(self, execution_result: dict[str, Any]) -> float:
        """Assess confidence in execution results.

        Signals that reduce confidence:
          - Agent failures (status != completed)
          - High retry counts
          - Missing expected outputs
          - Timeout events
        """
        if not execution_result:
            return 0.0

        stage_results = execution_result.get("stage_results", [])
        if not stage_results:
            return 0.5

        total_stages = len(stage_results)
        completed_stages = sum(
            1 for r in stage_results if r.get("status") == "COMPLETED"
        )
        total_retries = sum(r.get("retry_count", 0) for r in stage_results)

        confidence = completed_stages / max(total_stages, 1)
        confidence -= total_retries * 0.1

        timeouts = sum(1 for r in stage_results if r.get("status") == "TIMED_OUT")
        confidence -= timeouts * 0.3

        return max(0.0, min(1.0, confidence))

    def _fallback_plan(
        self,
        task_id: str,
        task_description: str,
        organism_level: str,
    ) -> WorkflowPlan:
        """Generate a simple fallback plan when Conductor reasoning fails."""
        return WorkflowPlan(
            task_id=task_id,
            organism_level=organism_level,
            topology_type=TopologyType.SEQUENTIAL,
            steps=[
                WorkflowStep(
                    step_index=0,
                    subtask="Analyze the task requirements and plan the implementation approach",
                    agent_role="fde-tech-lead-agent",
                    model_tier="reasoning",
                    access_list=[],
                ),
                WorkflowStep(
                    step_index=1,
                    subtask="Implement the solution following the plan from the previous step",
                    agent_role="swe-developer-agent",
                    model_tier="reasoning",
                    access_list=["all"],
                ),
                WorkflowStep(
                    step_index=2,
                    subtask="Validate the implementation against requirements and report findings",
                    agent_role="fde-fidelity-agent",
                    model_tier="fast",
                    access_list=["all"],
                ),
            ],
            planning_rationale="Fallback plan: sequential planning -> implementation -> validation",
        )
