"""
File Scanner — Walks the filesystem and classifies every file by content type
using Google's Magika library.

Design ref: §3.3 File Scanner (Magika)
"""

import logging
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Generator, Optional

from magika import Magika

logger = logging.getLogger("fde-onboarding.file_scanner")

# Directories to skip for performance (REQ-2.5)
SKIP_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "vendor",
    "dist",
    "build",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".next",
    ".nuxt",
    "target",  # Rust/Java build output
    ".terraform",
    ".build",
}

# Max binary file size to skip (1MB)
MAX_BINARY_SIZE = 1_048_576

# Patterns indicating generated code
GENERATED_MARKERS = [
    re.compile(r"auto[- ]?generated", re.IGNORECASE),
    re.compile(r"DO NOT EDIT", re.IGNORECASE),
    re.compile(r"@generated", re.IGNORECASE),
    re.compile(r"generated by", re.IGNORECASE),
    re.compile(r"this file is generated", re.IGNORECASE),
]

# Known generated file paths
GENERATED_PATHS = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Pipfile.lock",
    "poetry.lock",
    "Cargo.lock",
    "go.sum",
    "composer.lock",
}


@dataclass
class FileRecord:
    """Classification result for a single file."""

    path: str  # Relative to workspace root
    magika_type: str
    language: str
    size_bytes: int
    is_generated: bool


@dataclass
class ScanResult:
    """Aggregate result of the file scanning stage."""

    files: list[FileRecord]
    total_files_scanned: int
    total_files_skipped: int
    scan_duration_ms: int
    errors: list[str]


def scan_files(
    workspace_path: str,
    max_files: int = 100_000,
    gitignore_patterns: Optional[list[str]] = None,
) -> ScanResult:
    """
    Walk the workspace and classify all files using Magika.

    Args:
        workspace_path: Root directory to scan.
        max_files: Maximum files to process (sampling kicks in above this).
        gitignore_patterns: Additional patterns to skip.

    Returns:
        ScanResult with classified files and metadata.
    """
    start = time.time()
    magika = Magika()

    files: list[FileRecord] = []
    errors: list[str] = []
    skipped = 0

    for record in _walk_and_classify(workspace_path, magika, max_files):
        if isinstance(record, FileRecord):
            files.append(record)
        else:
            # Error string
            errors.append(record)
            skipped += 1

    duration_ms = int((time.time() - start) * 1000)

    logger.info(
        "File scan complete: %d files classified, %d skipped, %d errors, %dms",
        len(files),
        skipped,
        len(errors),
        duration_ms,
    )

    return ScanResult(
        files=files,
        total_files_scanned=len(files),
        total_files_skipped=skipped,
        scan_duration_ms=duration_ms,
        errors=errors,
    )


def _walk_and_classify(
    workspace_path: str,
    magika: Magika,
    max_files: int,
) -> Generator[FileRecord | str, None, None]:
    """Walk filesystem and yield FileRecord or error string for each file."""
    workspace = Path(workspace_path)
    count = 0

    for dirpath, dirnames, filenames in os.walk(workspace_path):
        # Prune skip directories in-place
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]

        for filename in filenames:
            if count >= max_files:
                logger.warning("Max files reached (%d), stopping scan", max_files)
                return

            filepath = Path(dirpath) / filename
            rel_path = str(filepath.relative_to(workspace))

            try:
                record = _classify_file(filepath, rel_path, magika)
                if record:
                    yield record
                    count += 1
            except Exception as e:
                yield f"Error classifying {rel_path}: {e}"


def _classify_file(
    filepath: Path,
    rel_path: str,
    magika: Magika,
) -> Optional[FileRecord]:
    """Classify a single file with Magika. Returns None if file should be skipped."""
    if not filepath.is_file():
        return None

    size_bytes = filepath.stat().st_size

    # Skip large binary files
    if size_bytes > MAX_BINARY_SIZE:
        try:
            with open(filepath, "rb") as f:
                chunk = f.read(512)
                if b"\x00" in chunk:
                    return None  # Binary file, skip
        except (OSError, PermissionError):
            return None

    # Classify with Magika
    try:
        result = magika.identify_path(filepath)
        magika_type = result.output.ct_label
        language = result.output.group
    except Exception:
        # Fallback: use extension
        magika_type = "unknown"
        language = filepath.suffix.lstrip(".") or "unknown"

    # Detect generated files
    is_generated = _detect_generated(filepath, rel_path)

    return FileRecord(
        path=rel_path,
        magika_type=magika_type,
        language=language,
        size_bytes=size_bytes,
        is_generated=is_generated,
    )


def _detect_generated(filepath: Path, rel_path: str) -> bool:
    """Detect if a file is auto-generated."""
    # Check known generated file names
    filename = filepath.name
    if filename in GENERATED_PATHS:
        return True

    # Check header comments for generated markers
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            header = ""
            for i, line in enumerate(f):
                if i >= 5:
                    break
                header += line

        for pattern in GENERATED_MARKERS:
            if pattern.search(header):
                return True
    except (OSError, PermissionError):
        pass

    return False
