"""
Steering Generator — Generates a project-specific .kiro/steering/fde.md file
from the catalog data.

Design ref: §3.8 Steering Generator
"""

import difflib
import logging
import os
import sqlite3
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger("fde-onboarding.steering_generator")


@dataclass
class SteeringResult:
    """Result of steering generation."""

    steering_md: str
    steering_diff: str  # Empty on first run
    output_path: str
    duration_ms: int


def generate_steering(
    catalog_path: str,
    repo_name: str,
    commit_sha: str,
    output_path: str,
    existing_steering_path: Optional[str] = None,
) -> SteeringResult:
    """
    Generate a project-specific FDE steering file from the catalog.

    Args:
        catalog_path: Path to the SQLite catalog.
        repo_name: Repository name for the header.
        commit_sha: Current commit SHA.
        output_path: Where to write the steering draft.
        existing_steering_path: Path to current steering (for diff on re-scan).

    Returns:
        SteeringResult with the generated markdown and diff.
    """
    start = time.time()

    conn = sqlite3.connect(catalog_path)
    try:
        pipeline_chain = conn.execute(
            "SELECT step_order, module_name, produces, consumes FROM pipeline_chain ORDER BY step_order"
        ).fetchall()

        module_boundaries = conn.execute(
            "SELECT edge_id, producer, consumer, transform_description FROM module_boundaries"
        ).fetchall()

        tech_stack = conn.execute(
            "SELECT tag, category, confidence FROM tech_stack ORDER BY category, tag"
        ).fetchall()

        level_patterns = conn.execute(
            "SELECT pattern, level, description FROM level_patterns ORDER BY level, pattern"
        ).fetchall()

        conventions = conn.execute(
            "SELECT category, name, config_path FROM conventions ORDER BY category, name"
        ).fetchall()
    finally:
        conn.close()

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    steering_md = _render_steering(
        repo_name=repo_name,
        date_str=date_str,
        catalog_path=catalog_path,
        commit_sha=commit_sha,
        pipeline_chain=pipeline_chain,
        module_boundaries=module_boundaries,
        tech_stack=tech_stack,
        level_patterns=level_patterns,
        conventions=conventions,
    )

    # Generate diff if existing steering exists (REQ-5.3)
    steering_diff = ""
    if existing_steering_path and os.path.isfile(existing_steering_path):
        try:
            with open(existing_steering_path, "r") as f:
                current_steering = f.read()
            steering_diff = _generate_diff(current_steering, steering_md)
        except OSError:
            pass

    # Write the steering draft
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(steering_md)

    duration_ms = int((time.time() - start) * 1000)

    logger.info(
        "Steering generated: %s (%d chars, diff=%d lines, %dms)",
        output_path, len(steering_md),
        len(steering_diff.splitlines()) if steering_diff else 0, duration_ms,
    )

    return SteeringResult(
        steering_md=steering_md,
        steering_diff=steering_diff,
        output_path=output_path,
        duration_ms=duration_ms,
    )


def _render_steering(
    repo_name: str, date_str: str, catalog_path: str, commit_sha: str,
    pipeline_chain: list, module_boundaries: list, tech_stack: list,
    level_patterns: list, conventions: list,
) -> str:
    """Render the full steering markdown from catalog data."""
    sections = []

    sections.append("---\ninclusion: manual\n---\n")
    sections.append(f"# Forward Deployed AI Engineer (FDE) — {repo_name}\n")
    sections.append(f"> Auto-generated by Repo Onboarding Agent on {date_str}")
    sections.append(f"> Catalog: {catalog_path}")
    sections.append(f"> Commit: {commit_sha}\n")

    # Pipeline Chain
    sections.append("## Pipeline Chain\n")
    if pipeline_chain:
        chain_parts = [module_name for _, module_name, _, _ in pipeline_chain]
        sections.append(f"```\n{' → '.join(chain_parts)}\n```\n")
        sections.append("| Step | Module | Consumes | Produces |")
        sections.append("|------|--------|----------|----------|")
        for step_order, module_name, produces, consumes in pipeline_chain:
            sections.append(f"| {step_order} | {module_name} | {consumes or '—'} | {produces or '—'} |")
    else:
        sections.append("_No pipeline chain inferred._")
    sections.append("")

    # Module Boundaries
    sections.append("## Module Boundaries (Where Bugs Live)\n")
    if module_boundaries:
        sections.append("| Edge | Producer | Consumer | What Transforms |")
        sections.append("|------|----------|----------|-----------------|")
        for edge_id, producer, consumer, transform in module_boundaries:
            sections.append(f"| {edge_id} | {producer} | {consumer} | {transform or '—'} |")
    else:
        sections.append("_No module boundaries inferred._")
    sections.append("")

    # Tech Stack
    sections.append("## Tech Stack\n")
    if tech_stack:
        categories: dict[str, list[str]] = {}
        for tag, category, confidence in tech_stack:
            categories.setdefault(category, []).append(tag)
        for category, tags in sorted(categories.items()):
            sections.append(f"- **{category}**: {', '.join(tags)}")
    else:
        sections.append("_No tech stack detected._")
    sections.append("")

    # Engineering Level Patterns
    sections.append("## Engineering Level Patterns\n")
    if level_patterns:
        sections.append("| Pattern | Level | Description |")
        sections.append("|---------|-------|-------------|")
        for pattern, level, description in level_patterns:
            sections.append(f"| {pattern} | {level} | {description or '—'} |")
    else:
        sections.append("_No level patterns inferred._")
    sections.append("")

    # Quality Reference Artifacts
    sections.append("## Quality Reference Artifacts\n")
    if conventions:
        conv_categories: dict[str, list[str]] = {}
        for category, name, config_path in conventions:
            entry = f"{name}" + (f" (`{config_path}`)" if config_path else "")
            conv_categories.setdefault(category, []).append(entry)
        for category, entries in sorted(conv_categories.items()):
            sections.append(f"### {category.replace('_', ' ').title()}")
            for entry in entries:
                sections.append(f"- {entry}")
            sections.append("")
    else:
        sections.append("_No conventions detected._")
    sections.append("")

    return "\n".join(sections)


def _generate_diff(current: str, proposed: str) -> str:
    """Produce a unified diff between current and proposed steering."""
    return "\n".join(difflib.unified_diff(
        current.splitlines(),
        proposed.splitlines(),
        fromfile="current-steering.md",
        tofile="proposed-steering.md",
        lineterm="",
    ))
