#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# Bootstrap FDE Workspace — Install FDE hooks into a target project
# ═══════════════════════════════════════════════════════════════════
#
# Installs the minimal FDE client scaffolding into any target workspace.
# After running this, the target project can:
#   - Trigger repo onboarding (generates steering)
#   - Receive tasks from the Code Factory pipeline
#
# Usage:
#   bash scripts/bootstrap-fde-workspace.sh --target /path/to/cognitive-wafr
#
# What it installs:
#   .kiro/hooks/fde-repo-onboard.kiro.hook  — Onboarding trigger
#   .kiro/hooks/fde-work-intake.kiro.hook   — Task intake trigger
#   .kiro/steering/                          — Directory for generated steering
#   .kiro/README.md                          — Quick reference
#
# What it does NOT install:
#   - The full FDE infrastructure (lives in forward-deployed-ai-pattern)
#   - The steering file (generated by the onboarding agent)
#   - Any production code or agents
# ═══════════════════════════════════════════════════════════════════

set -uo pipefail

TARGET=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --target) TARGET="$2"; shift 2 ;;
    *) echo "Usage: bash scripts/bootstrap-fde-workspace.sh --target /path/to/project"; exit 1 ;;
  esac
done

if [[ -z "$TARGET" ]]; then
  echo "❌ --target is required. Path to the project workspace."
  exit 1
fi

if [[ ! -d "$TARGET" ]]; then
  echo "❌ Target directory does not exist: $TARGET"
  exit 1
fi

echo ""
echo "━━━ Bootstrap FDE Workspace ━━━"
echo "  Target: $TARGET"
echo ""

mkdir -p "$TARGET/.kiro/hooks"
mkdir -p "$TARGET/.kiro/steering"

echo "① Installing hooks..."

cat > "$TARGET/.kiro/hooks/fde-repo-onboard.kiro.hook" << 'HOOK'
{
  "name": "FDE Repo Onboard",
  "version": "1.0.0",
  "description": "Scans this workspace and generates a project-specific FDE steering file. Run once after cloning, or when the codebase structure changes significantly.",
  "when": {
    "type": "userTriggered"
  },
  "then": {
    "type": "askAgent",
    "prompt": "Run the Repo Onboarding Agent in local mode against this workspace. Scan the codebase structure using file type detection and AST extraction, detect project conventions (languages, frameworks, test tools, CI/CD, IaC), and generate a project-specific FDE steering file at .kiro/steering/fde-draft.md. The steering should contain: pipeline chain, module boundaries, tech stack tags, and engineering level patterns. After generation, report a summary of what was found."
  }
}
HOOK
echo "  ✅ fde-repo-onboard.kiro.hook"

cat > "$TARGET/.kiro/hooks/fde-work-intake.kiro.hook" << 'HOOK'
{
  "name": "FDE Work Intake",
  "version": "1.0.0",
  "description": "Scans connected ALM platforms for tasks labeled 'factory-ready' and creates spec files for the FDE pipeline.",
  "when": {
    "type": "userTriggered"
  },
  "then": {
    "type": "askAgent",
    "prompt": "Scan GitHub issues for this repository that have the 'factory-ready' label. For each issue found, create a spec file in .kiro/specs/ with the issue title, body, labels, and acceptance criteria mapped to the canonical task schema. Set the spec status to 'ready' so the FDE pipeline can pick it up. Report which issues were processed."
  }
}
HOOK
echo "  ✅ fde-work-intake.kiro.hook"

cat > "$TARGET/.kiro/README.md" << 'README'
# FDE Integration

This workspace is connected to the Code Factory (Forward Deployed AI Engineer pattern).

## Hooks

| Hook | Trigger | What It Does |
|------|---------|-------------|
| `fde-repo-onboard` | Manual (click play) | Scans codebase, generates steering |
| `fde-work-intake` | Manual (click play) | Reads GitHub issues, creates specs |

## Steering

- `fde-draft.md` — Generated by onboarding, pending review
- `fde.md` — Active (renamed from draft after approval)

## Getting Started

1. Trigger `fde-repo-onboard` to generate steering
2. Review `.kiro/steering/fde-draft.md` then rename to `fde.md`
3. Label GitHub issues with `factory-ready` to trigger the pipeline
README
echo "  ✅ .kiro/README.md"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  🟢 FDE workspace bootstrapped: $TARGET"
echo ""
echo "  Next: Open $TARGET in Kiro → trigger fde-repo-onboard"
echo "═══════════════════════════════════════════════════════════"
